#!/usr/bin/env python3
"""
BlockCraft Bedrock Add-on Deployment API
Generates and deploys Minecraft Bedrock Edition behavior packs

Note: Bedrock add-ons use:
- JSON for entity/item definitions
- JavaScript for scripting (@minecraft/server API)
- .mcfunction files for commands
- No compilation needed (just packaging)
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import os
import json
import shutil
import hashlib
import uuid
import zipfile

app = Flask(__name__)
CORS(app, resources={
    r"/api/*": {
        "origins": "*",
        "methods": ["GET", "POST", "OPTIONS"],
        "allow_headers": ["Content-Type"]
    }
})

# Paths - TODO: Configure for your Bedrock installation
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), 'bedrock-addon-template')
BUILD_PATH = '/tmp/bedrock-addon-build'
# Bedrock worlds path varies by platform:
# Windows: %LOCALAPPDATA%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\behavior_packs
# Android: /storage/emulated/0/games/com.mojang/behavior_packs
BEDROCK_PACKS_PATH = os.path.expanduser('~/bedrock_packs')  # TODO: Update this path

def generate_uuid():
    """Generate a random UUID for manifests"""
    return str(uuid.uuid4())

def calculate_sha1(file_path):
    """Calculate SHA1 hash of a file"""
    sha1 = hashlib.sha1()
    with open(file_path, 'rb') as f:
        while chunk := f.read(8192):
            sha1.update(chunk)
    return sha1.hexdigest()

@app.route('/api/deploy', methods=['POST', 'OPTIONS'])
def deploy_bedrock_addon():
    """
    Receives Bedrock code from the web editor and packages it as an add-on
    """
    # Handle CORS preflight request
    if request.method == 'OPTIONS':
        return '', 200

    try:
        data = request.json

        if not data:
            return jsonify({'success': False, 'error': 'No data provided'}), 400

        # Get project info
        project_id = data.get('projectId', 'default')
        project_name = data.get('projectName', 'BlockCraft Addon')
        safe_project_id = project_id.replace('project_', '').replace('_', '')

        # Custom items/mobs work differently in Bedrock (JSON-based)
        custom_items = data.get('customItems', [])
        custom_mobs = data.get('customMobs', [])

        # Clean and prepare build directory
        if os.path.exists(BUILD_PATH):
            shutil.rmtree(BUILD_PATH)

        # Check if template exists
        if not os.path.exists(TEMPLATE_PATH):
            return jsonify({
                'success': False,
                'error': f'Bedrock addon template not found at: {TEMPLATE_PATH}\\n\\nPlease create a Bedrock addon template first.'
            }), 500

        shutil.copytree(TEMPLATE_PATH, BUILD_PATH)

        # Generate UUIDs for this addon
        header_uuid = generate_uuid()
        module_uuid = generate_uuid()
        script_uuid = generate_uuid()

        # Generate manifest.json
        manifest = {
            "format_version": 2,
            "header": {
                "name": project_name,
                "description": f"Generated by BlockCraft - {project_name}",
                "uuid": header_uuid,
                "version": [1, 0, 0],
                "min_engine_version": [1, 21, 0]
            },
            "modules": [
                {
                    "type": "data",
                    "uuid": module_uuid,
                    "version": [1, 0, 0]
                },
                {
                    "type": "script",
                    "language": "javascript",
                    "uuid": script_uuid,
                    "entry": "scripts/main.js",
                    "version": [1, 0, 0]
                }
            ],
            "dependencies": [
                {
                    "module_name": "@minecraft/server",
                    "version": "1.9.0-beta"
                }
            ]
        }

        manifest_path = os.path.join(BUILD_PATH, 'manifest.json')
        with open(manifest_path, 'w') as f:
            json.dump(manifest, f, indent=2)

        # Get generated code from frontend
        commands = data.get('commands', [])
        events = data.get('events', [])

        # Generate main JavaScript file
        scripts_dir = os.path.join(BUILD_PATH, 'scripts')
        os.makedirs(scripts_dir, exist_ok=True)

        javascript_code = """import { world, system } from "@minecraft/server";

// BlockCraft Generated Addon
// Project: """ + project_name + """

"""

        # Add command handlers
        if commands:
            javascript_code += """
// Command Handlers
"""
            for cmd in commands:
                cmd_name = cmd.get('name', '')
                cmd_code = cmd.get('code', {}).get('javascript', '')

                if cmd_name and cmd_code:
                    javascript_code += f"""
// Command: /{cmd_name}
world.beforeEvents.chatSend.subscribe((event) => {{
    if (event.message.toLowerCase() === '/{cmd_name}') {{
        event.cancel = true;
        const player = event.sender;
{cmd_code}
    }}
}});
"""

        # Add event listeners
        if events:
            javascript_code += """
// Event Listeners
"""
            for evt in events:
                evt_type = evt.get('type', '')
                evt_code = evt.get('code', {}).get('javascript', '')

                if evt_type == 'block_break' and evt_code:
                    javascript_code += f"""
// Block Break Event
world.beforeEvents.playerBreakBlock.subscribe((event) => {{
    const player = event.player;
    const block = event.block;
{evt_code}
}});
"""
                elif evt_type == 'right_click' and evt_code:
                    javascript_code += f"""
// Item Use Event
world.beforeEvents.itemUse.subscribe((event) => {{
    const player = event.source;
{evt_code}
}});
"""

        javascript_code += """
console.log("[BlockCraft] Addon loaded successfully!");
"""

        main_js_path = os.path.join(scripts_dir, 'main.js')
        with open(main_js_path, 'w') as f:
            f.write(javascript_code)

        # Generate .mcfunction files for commands
        functions_dir = os.path.join(BUILD_PATH, 'functions')
        os.makedirs(functions_dir, exist_ok=True)

        for cmd in commands:
            cmd_name = cmd.get('name', '')
            cmd_mcfunction = cmd.get('code', {}).get('mcfunction', '')

            if cmd_name and cmd_mcfunction:
                function_path = os.path.join(functions_dir, f'{cmd_name}.mcfunction')
                with open(function_path, 'w') as f:
                    f.write(f"# Command: /{cmd_name}\\n")
                    f.write(cmd_mcfunction)

        # TODO: Generate entity JSON files for custom mobs
        if custom_mobs:
            entities_dir = os.path.join(BUILD_PATH, 'entities')
            os.makedirs(entities_dir, exist_ok=True)
            # Bedrock entity definitions would go here

        # TODO: Generate item JSON files for custom items
        if custom_items:
            items_dir = os.path.join(BUILD_PATH, 'items')
            os.makedirs(items_dir, exist_ok=True)
            # Bedrock item definitions would go here

        # Package as .mcpack (ZIP file)
        pack_filename = f'blockcraft-{safe_project_id}.mcpack'
        pack_path = os.path.join('/tmp', pack_filename)

        with zipfile.ZipFile(pack_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files in os.walk(BUILD_PATH):
                for file in files:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, BUILD_PATH)
                    zipf.write(file_path, arcname)

        print(f"📦 Created Bedrock add-on: {pack_path}")

        # Deploy to packs folder
        should_deploy = data.get('deploy', True)

        if should_deploy:
            os.makedirs(BEDROCK_PACKS_PATH, exist_ok=True)
            target_pack = os.path.join(BEDROCK_PACKS_PATH, pack_filename)
            shutil.copy(pack_path, target_pack)
            print(f"📦 Deployed to: {target_pack}")
        else:
            # Just build - copy to Downloads
            home_dir = os.path.expanduser("~")
            downloads_dir = os.path.join(home_dir, "Downloads")
            os.makedirs(downloads_dir, exist_ok=True)
            target_pack = os.path.join(downloads_dir, pack_filename)
            shutil.copy(pack_path, target_pack)
            print(f"📦 Saved to: {target_pack}")

        # Get command list
        cmd_names = [cmd['name'] for cmd in commands]
        if cmd_names:
            cmd_list = '\\n'.join([f'  /{name}' for name in cmd_names])
        else:
            cmd_list = '  (No commands - this addon uses events only)'

        # Create success message
        if should_deploy:
            success_msg = f'''✅ Bedrock add-on created successfully!

🎮 Your custom commands:
{cmd_list}

📦 Add-on file: {target_pack}

📱 To install:
1. Copy the .mcpack file to your device
2. Open it with Minecraft Bedrock
3. It will be imported automatically
4. Enable it in World Settings > Behavior Packs
'''
        else:
            success_msg = f'''✅ Bedrock add-on built successfully!

🎮 Your custom commands:
{cmd_list}

📦 Add-on saved to: {target_pack}

📱 To install:
1. Copy the .mcpack file to your device
2. Open it with Minecraft Bedrock
3. It will be imported automatically
'''

        return jsonify({
            'success': True,
            'message': success_msg,
            'pack_file': pack_filename,
            'pack_path': target_pack,
            'project_name': project_name
        })

    except Exception as e:
        import traceback
        error_msg = f"{str(e)}\\n\\nTraceback:\\n{traceback.format_exc()}"
        print(f"ERROR: {error_msg}")
        return jsonify({'success': False, 'error': error_msg}), 500

@app.route('/health', methods=['GET'])
def health():
    """Check if API is running"""
    return jsonify({'status': 'ok', 'mode': 'bedrock'})

if __name__ == '__main__':
    print("🚀 BlockCraft Bedrock Deployment API Starting...")
    print(f"📁 Template path: {TEMPLATE_PATH}")
    print(f"📁 Bedrock packs path: {BEDROCK_PACKS_PATH}")
    print(f"🌐 API running on: http://localhost:8587")
    print(f"")
    print("Note: Bedrock uses JSON + JavaScript (no compilation needed)")
    print("Press Ctrl+C to stop")
    print("=" * 60)
    app.run(host='0.0.0.0', port=8587, debug=True)
