/**
 * Complete lists of all Minecraft items, blocks, and entities
 * Generated from Faithful texture pack
 */

import type { MenuOption } from 'blockly';

export const ALL_ITEMS: MenuOption[] = [
  ['Acacia Boat', 'acacia_boat'],
  ['Acacia Door', 'acacia_door'],
  ['Acacia Sign', 'acacia_sign'],
  ['Amethyst Shard', 'amethyst_shard'],
  ['Apple', 'apple'],
  ['Armor Stand', 'armor_stand'],
  ['Arrow', 'arrow'],
  ['Axolotl Bucket', 'axolotl_bucket'],
  ['Baked Potato', 'baked_potato'],
  ['Bamboo', 'bamboo'],
  ['Barrier', 'barrier'],
  ['Beef', 'beef'],
  ['Beetroot', 'beetroot'],
  ['Beetroot Seeds', 'beetroot_seeds'],
  ['Beetroot Soup', 'beetroot_soup'],
  ['Bell', 'bell'],
  ['Birch Boat', 'birch_boat'],
  ['Birch Door', 'birch_door'],
  ['Birch Sign', 'birch_sign'],
  ['Black Dye', 'black_dye'],
  ['Blaze Powder', 'blaze_powder'],
  ['Blaze Rod', 'blaze_rod'],
  ['Blue Dye', 'blue_dye'],
  ['Bone', 'bone'],
  ['Bone Meal', 'bone_meal'],
  ['Book', 'book'],
  ['Bow', 'bow'],
  ['Bowl', 'bowl'],
  ['Bread', 'bread'],
  ['Brewing Stand', 'brewing_stand'],
  ['Brick', 'brick'],
  ['Brown Dye', 'brown_dye'],
  ['Brush', 'brush'],
  ['Bucket', 'bucket'],
  ['Bundle', 'bundle'],
  ['Carrot', 'carrot'],
  ['Carrot On A Stick', 'carrot_on_a_stick'],
  ['Cauldron', 'cauldron'],
  ['Chainmail Boots', 'chainmail_boots'],
  ['Chainmail Chestplate', 'chainmail_chestplate'],
  ['Chainmail Helmet', 'chainmail_helmet'],
  ['Chainmail Leggings', 'chainmail_leggings'],
  ['Charcoal', 'charcoal'],
  ['Chest Minecart', 'chest_minecart'],
  ['Chicken', 'chicken'],
  ['Chorus Fruit', 'chorus_fruit'],
  ['Clay Ball', 'clay_ball'],
  ['Clock', 'clock'],
  ['Coal', 'coal'],
  ['Cocoa Beans', 'cocoa_beans'],
  ['Cod', 'cod'],
  ['Cod Bucket', 'cod_bucket'],
  ['Command Block Minecart', 'command_block_minecart'],
  ['Comparator', 'comparator'],
  ['Compass', 'compass'],
  ['Cooked Beef', 'cooked_beef'],
  ['Cooked Chicken', 'cooked_chicken'],
  ['Cooked Cod', 'cooked_cod'],
  ['Cooked Mutton', 'cooked_mutton'],
  ['Cooked Porkchop', 'cooked_porkchop'],
  ['Cooked Rabbit', 'cooked_rabbit'],
  ['Cooked Salmon', 'cooked_salmon'],
  ['Cookie', 'cookie'],
  ['Copper Ingot', 'copper_ingot'],
  ['Cow Spawn Egg', 'cow_spawn_egg'],
  ['Creeper Spawn Egg', 'creeper_spawn_egg'],
  ['Crimson Door', 'crimson_door'],
  ['Crimson Sign', 'crimson_sign'],
  ['Crossbow', 'crossbow'],
  ['Crossbow Arrow', 'crossbow_arrow'],
  ['Crossbow Firework', 'crossbow_firework'],
  ['Crossbow Pulling 0', 'crossbow_pulling_0'],
  ['Crossbow Pulling 1', 'crossbow_pulling_1'],
  ['Crossbow Pulling 2', 'crossbow_pulling_2'],
  ['Crossbow Standby', 'crossbow_standby'],
  ['Cyan Dye', 'cyan_dye'],
  ['Dark Oak Boat', 'dark_oak_boat'],
  ['Dark Oak Door', 'dark_oak_door'],
  ['Dark Oak Sign', 'dark_oak_sign'],
  ['Debug Stick', 'debug_stick'],
  ['Diamond', 'diamond'],
  ['Diamond Axe', 'diamond_axe'],
  ['Diamond Boots', 'diamond_boots'],
  ['Diamond Chestplate', 'diamond_chestplate'],
  ['Diamond Helmet', 'diamond_helmet'],
  ['Diamond Hoe', 'diamond_hoe'],
  ['Diamond Horse Armor', 'diamond_horse_armor'],
  ['Diamond Leggings', 'diamond_leggings'],
  ['Diamond Pickaxe', 'diamond_pickaxe'],
  ['Diamond Shovel', 'diamond_shovel'],
  ['Diamond Sword', 'diamond_sword'],
  ['Dragon Breath', 'dragon_breath'],
  ['Dried Kelp', 'dried_kelp'],
  ['Ech Fragment', 'echo_shard'],
  ['Egg', 'egg'],
  ['Elytra', 'elytra'],
  ['Emerald', 'emerald'],
  ['Enchanted Book', 'enchanted_book'],
  ['Enchanted Golden Apple', 'enchanted_golden_apple'],
  ['End Crystal', 'end_crystal'],
  ['Ender Eye', 'ender_eye'],
  ['Ender Pearl', 'ender_pearl'],
  ['Experience Bottle', 'experience_bottle'],
  ['Feather', 'feather'],
  ['Fermented Spider Eye', 'fermented_spider_eye'],
  ['Fire Charge', 'fire_charge'],
  ['Firework Rocket', 'firework_rocket'],
  ['Firework Star', 'firework_star'],
  ['Firework Star Overlay', 'firework_star_overlay'],
  ['Fishing Rod', 'fishing_rod'],
  ['Fishing Rod Cast', 'fishing_rod_cast'],
  ['Flint', 'flint'],
  ['Flint And Steel', 'flint_and_steel'],
  ['Flower Pot', 'flower_pot'],
  ['Furnace Minecart', 'furnace_minecart'],
  ['Ghast Tear', 'ghast_tear'],
  ['Glistering Melon Slice', 'glistering_melon_slice'],
  ['Glow Berries', 'glow_berries'],
  ['Glow Ink Sac', 'glow_ink_sac'],
  ['Glow Item Frame', 'glow_item_frame'],
  ['Glowstone Dust', 'glowstone_dust'],
  ['Goat Horn', 'goat_horn'],
  ['Gold Ingot', 'gold_ingot'],
  ['Gold Nugget', 'gold_nugget'],
  ['Golden Apple', 'golden_apple'],
  ['Golden Axe', 'golden_axe'],
  ['Golden Boots', 'golden_boots'],
  ['Golden Carrot', 'golden_carrot'],
  ['Golden Chestplate', 'golden_chestplate'],
  ['Golden Helmet', 'golden_helmet'],
  ['Golden Hoe', 'golden_hoe'],
  ['Golden Horse Armor', 'golden_horse_armor'],
  ['Golden Leggings', 'golden_leggings'],
  ['Golden Pickaxe', 'golden_pickaxe'],
  ['Golden Shovel', 'golden_shovel'],
  ['Golden Sword', 'golden_sword'],
  ['Gray Dye', 'gray_dye'],
  ['Green Dye', 'green_dye'],
  ['Gunpowder', 'gunpowder'],
  ['Heart Of The Sea', 'heart_of_the_sea'],
  ['Honey Bottle', 'honey_bottle'],
  ['Honeycomb', 'honeycomb'],
  ['Hopper', 'hopper'],
  ['Hopper Minecart', 'hopper_minecart'],
  ['Ink Sac', 'ink_sac'],
  ['Iron Axe', 'iron_axe'],
  ['Iron Boots', 'iron_boots'],
  ['Iron Chestplate', 'iron_chestplate'],
  ['Iron Door', 'iron_door'],
  ['Iron Helmet', 'iron_helmet'],
  ['Iron Hoe', 'iron_hoe'],
  ['Iron Horse Armor', 'iron_horse_armor'],
  ['Iron Ingot', 'iron_ingot'],
  ['Iron Leggings', 'iron_leggings'],
  ['Iron Nugget', 'iron_nugget'],
  ['Iron Pickaxe', 'iron_pickaxe'],
  ['Iron Shovel', 'iron_shovel'],
  ['Iron Sword', 'iron_sword'],
  ['Item Frame', 'item_frame'],
  ['Jungle Boat', 'jungle_boat'],
  ['Jungle Door', 'jungle_door'],
  ['Jungle Sign', 'jungle_sign'],
  ['Knowledge Book', 'knowledge_book'],
  ['Lapis Lazuli', 'lapis_lazuli'],
  ['Lava Bucket', 'lava_bucket'],
  ['Lead', 'lead'],
  ['Leather', 'leather'],
  ['Leather Boots', 'leather_boots'],
  ['Leather Chestplate', 'leather_chestplate'],
  ['Leather Helmet', 'leather_helmet'],
  ['Leather Horse Armor', 'leather_horse_armor'],
  ['Leather Leggings', 'leather_leggings'],
  ['Light Blue Dye', 'light_blue_dye'],
  ['Light Gray Dye', 'light_gray_dye'],
  ['Lime Dye', 'lime_dye'],
  ['Lingering Potion', 'lingering_potion'],
  ['Magenta Dye', 'magenta_dye'],
  ['Magma Cream', 'magma_cream'],
  ['Mangrove Boat', 'mangrove_boat'],
  ['Mangrove Door', 'mangrove_door'],
  ['Mangrove Sign', 'mangrove_sign'],
  ['Map', 'map'],
  ['Melon Seeds', 'melon_seeds'],
  ['Melon Slice', 'melon_slice'],
  ['Milk Bucket', 'milk_bucket'],
  ['Minecart', 'minecart'],
  ['Mushroom Stew', 'mushroom_stew'],
  ['Music Disc 11', 'music_disc_11'],
  ['Music Disc 13', 'music_disc_13'],
  ['Music Disc 5', 'music_disc_5'],
  ['Music Disc Blocks', 'music_disc_blocks'],
  ['Music Disc Cat', 'music_disc_cat'],
  ['Music Disc Chirp', 'music_disc_chirp'],
  ['Music Disc Far', 'music_disc_far'],
  ['Music Disc Mall', 'music_disc_mall'],
  ['Music Disc Mellohi', 'music_disc_mellohi'],
  ['Music Disc Otherside', 'music_disc_otherside'],
  ['Music Disc Pigstep', 'music_disc_pigstep'],
  ['Music Disc Stal', 'music_disc_stal'],
  ['Music Disc Strad', 'music_disc_strad'],
  ['Music Disc Wait', 'music_disc_wait'],
  ['Music Disc Ward', 'music_disc_ward'],
  ['Mutton', 'mutton'],
  ['Name Tag', 'name_tag'],
  ['Nautilus Shell', 'nautilus_shell'],
  ['Nether Brick', 'nether_brick'],
  ['Nether Star', 'nether_star'],
  ['Nether Wart', 'nether_wart'],
  ['Netherite Axe', 'netherite_axe'],
  ['Netherite Boots', 'netherite_boots'],
  ['Netherite Chestplate', 'netherite_chestplate'],
  ['Netherite Helmet', 'netherite_helmet'],
  ['Netherite Hoe', 'netherite_hoe'],
  ['Netherite Ingot', 'netherite_ingot'],
  ['Netherite Leggings', 'netherite_leggings'],
  ['Netherite Pickaxe', 'netherite_pickaxe'],
  ['Netherite Scrap', 'netherite_scrap'],
  ['Netherite Shovel', 'netherite_shovel'],
  ['Netherite Sword', 'netherite_sword'],
  ['Oak Boat', 'oak_boat'],
  ['Oak Door', 'oak_door'],
  ['Oak Sign', 'oak_sign'],
  ['Orange Dye', 'orange_dye'],
  ['Painting', 'painting'],
  ['Paper', 'paper'],
  ['Phantom Membrane', 'phantom_membrane'],
  ['Pink Dye', 'pink_dye'],
  ['Poisonous Potato', 'poisonous_potato'],
  ['Popped Chorus Fruit', 'popped_chorus_fruit'],
  ['Porkchop', 'porkchop'],
  ['Potato', 'potato'],
  ['Potion', 'potion'],
  ['Powder Snow Bucket', 'powder_snow_bucket'],
  ['Prismarine Crystals', 'prismarine_crystals'],
  ['Prismarine Shard', 'prismarine_shard'],
  ['Pufferfish', 'pufferfish'],
  ['Pufferfish Bucket', 'pufferfish_bucket'],
  ['Pumpkin Pie', 'pumpkin_pie'],
  ['Pumpkin Seeds', 'pumpkin_seeds'],
  ['Purple Dye', 'purple_dye'],
  ['Quartz', 'quartz'],
  ['Rabbit', 'rabbit'],
  ['Rabbit Foot', 'rabbit_foot'],
  ['Rabbit Hide', 'rabbit_hide'],
  ['Rabbit Stew', 'rabbit_stew'],
  ['Raw Copper', 'raw_copper'],
  ['Raw Gold', 'raw_gold'],
  ['Raw Iron', 'raw_iron'],
  ['Recovery Compass', 'recovery_compass'],
  ['Red Dye', 'red_dye'],
  ['Redstone', 'redstone'],
  ['Repeater', 'repeater'],
  ['Rotten Flesh', 'rotten_flesh'],
  ['Saddle', 'saddle'],
  ['Salmon', 'salmon'],
  ['Salmon Bucket', 'salmon_bucket'],
  ['Scute', 'scute'],
  ['Shears', 'shears'],
  ['Shield', 'shield'],
  ['Shield Blocking', 'shield_blocking'],
  ['Shulker Shell', 'shulker_shell'],
  ['Slime Ball', 'slime_ball'],
  ['Snowball', 'snowball'],
  ['Spectral Arrow', 'spectral_arrow'],
  ['Spider Eye', 'spider_eye'],
  ['Splash Potion', 'splash_potion'],
  ['Spruce Boat', 'spruce_boat'],
  ['Spruce Door', 'spruce_door'],
  ['Spruce Sign', 'spruce_sign'],
  ['Spyglass', 'spyglass'],
  ['Stick', 'stick'],
  ['Stone Axe', 'stone_axe'],
  ['Stone Hoe', 'stone_hoe'],
  ['Stone Pickaxe', 'stone_pickaxe'],
  ['Stone Shovel', 'stone_shovel'],
  ['Stone Sword', 'stone_sword'],
  ['String', 'string'],
  ['Sugar', 'sugar'],
  ['Suspicious Stew', 'suspicious_stew'],
  ['Sweet Berries', 'sweet_berries'],
  ['Tadpole Bucket', 'tadpole_bucket'],
  ['Tipped Arrow', 'tipped_arrow'],
  ['Tnt Minecart', 'tnt_minecart'],
  ['Totem Of Undying', 'totem_of_undying'],
  ['Trident', 'trident'],
  ['Tropical Fish', 'tropical_fish'],
  ['Tropical Fish Bucket', 'tropical_fish_bucket'],
  ['Turtle Helmet', 'turtle_helmet'],
  ['Warped Door', 'warped_door'],
  ['Warped Fungus On A Stick', 'warped_fungus_on_a_stick'],
  ['Warped Sign', 'warped_sign'],
  ['Water Bucket', 'water_bucket'],
  ['Wheat', 'wheat'],
  ['Wheat Seeds', 'wheat_seeds'],
  ['White Dye', 'white_dye'],
  ['Wooden Axe', 'wooden_axe'],
  ['Wooden Hoe', 'wooden_hoe'],
  ['Wooden Pickaxe', 'wooden_pickaxe'],
  ['Wooden Shovel', 'wooden_shovel'],
  ['Wooden Sword', 'wooden_sword'],
  ['Writable Book', 'writable_book'],
  ['Written Book', 'written_book'],
  ['Yellow Dye', 'yellow_dye']
];

// Exporting a subset for common blocks (placeable)
export const ALL_BLOCKS: MenuOption[] = [
  ['Acacia Leaves', 'acacia_leaves'],
  ['Acacia Log', 'acacia_log'],
  ['Acacia Planks', 'acacia_planks'],
  ['Acacia Sapling', 'acacia_sapling'],
  ['Allium', 'allium'],
  ['Amethyst Block', 'amethyst_block'],
  ['Ancient Debris', 'ancient_debris_side'],
  ['Andesite', 'andesite'],
  ['Anvil', 'anvil'],
  ['Azalea Leaves', 'azalea_leaves'],
  ['Azure Bluet', 'azure_bluet'],
  ['Bamboo', 'bamboo_stalk'],
  ['Barrel', 'barrel_side'],
  ['Basalt', 'basalt_side'],
  ['Beacon', 'beacon'],
  ['Bedrock', 'bedrock'],
  ['Beehive', 'beehive_side'],
  ['Bee Nest', 'bee_nest_side'],
  ['Birch Leaves', 'birch_leaves'],
  ['Birch Log', 'birch_log'],
  ['Birch Planks', 'birch_planks'],
  ['Birch Sapling', 'birch_sapling'],
  ['Blackstone', 'blackstone'],
  ['Blast Furnace', 'blast_furnace_front'],
  ['Blue Ice', 'blue_ice'],
  ['Blue Orchid', 'blue_orchid'],
  ['Bone Block', 'bone_block_side'],
  ['Bookshelf', 'bookshelf'],
  ['Brain Coral Block', 'brain_coral_block'],
  ['Bricks', 'bricks'],
  ['Brown Mushroom Block', 'brown_mushroom_block'],
  ['Bubble Coral Block', 'bubble_coral_block'],
  ['Cactus', 'cactus_side'],
  ['Calcite', 'calcite'],
  ['Campfire', 'campfire_fire'],
  ['Carved Pumpkin', 'carved_pumpkin'],
  ['Chest', 'chest_front'],
  ['Chiseled Bookshelf', 'chiseled_bookshelf_empty'],
  ['Clay', 'clay'],
  ['Coal Block', 'coal_block'],
  ['Coal Ore', 'coal_ore'],
  ['Cobblestone', 'cobblestone'],
  ['Copper Block', 'copper_block'],
  ['Copper Ore', 'copper_ore'],
  ['Crafting Table', 'crafting_table_front'],
  ['Crimson Nylium', 'crimson_nylium'],
  ['Crimson Planks', 'crimson_planks'],
  ['Crying Obsidian', 'crying_obsidian'],
  ['Cut Copper', 'cut_copper'],
  ['Dandelion', 'dandelion'],
  ['Dark Oak Leaves', 'dark_oak_leaves'],
  ['Dark Oak Log', 'dark_oak_log'],
  ['Dark Oak Planks', 'dark_oak_planks'],
  ['Dark Oak Sapling', 'dark_oak_sapling'],
  ['Dark Prismarine', 'dark_prismarine'],
  ['Deepslate', 'deepslate'],
  ['Deepslate Bricks', 'deepslate_bricks'],
  ['Deepslate Coal Ore', 'deepslate_coal_ore'],
  ['Deepslate Copper Ore', 'deepslate_copper_ore'],
  ['Deepslate Diamond Ore', 'deepslate_diamond_ore'],
  ['Deepslate Emerald Ore', 'deepslate_emerald_ore'],
  ['Deepslate Gold Ore', 'deepslate_gold_ore'],
  ['Deepslate Iron Ore', 'deepslate_iron_ore'],
  ['Deepslate Lapis Ore', 'deepslate_lapis_ore'],
  ['Deepslate Redstone Ore', 'deepslate_redstone_ore'],
  ['Diamond Block', 'diamond_block'],
  ['Diamond Ore', 'diamond_ore'],
  ['Diorite', 'diorite'],
  ['Dirt', 'dirt'],
  ['Dirt Path', 'dirt_path_side'],
  ['Dispenser', 'dispenser_front'],
  ['Dragon Egg', 'dragon_egg'],
  ['Dried Kelp Block', 'dried_kelp_side'],
  ['Dripstone Block', 'dripstone_block'],
  ['Dropper', 'dropper_front'],
  ['Emerald Block', 'emerald_block'],
  ['Emerald Ore', 'emerald_ore'],
  ['End Stone', 'end_stone'],
  ['End Stone Bricks', 'end_stone_bricks'],
  ['Farmland', 'farmland'],
  ['Fire Coral Block', 'fire_coral_block'],
  ['Fletching Table', 'fletching_table_front'],
  ['Flowering Azalea Leaves', 'flowering_azalea_leaves'],
  ['Furnace', 'furnace_front'],
  ['Gilded Blackstone', 'gilded_blackstone'],
  ['Glass', 'glass'],
  ['Glowstone', 'glowstone'],
  ['Gold Block', 'gold_block'],
  ['Gold Ore', 'gold_ore'],
  ['Granite', 'granite'],
  ['Grass Block', 'grass_block_side'],
  ['Gravel', 'gravel'],
  ['Gray Concrete', 'gray_concrete'],
  ['Gray Wool', 'gray_wool'],
  ['Hay Block', 'hay_block_side'],
  ['Honeycomb Block', 'honeycomb_block'],
  ['Horn Coral Block', 'horn_coral_block'],
  ['Ice', 'ice'],
  ['Iron Block', 'iron_block'],
  ['Iron Ore', 'iron_ore'],
  ['Jack O Lantern', 'jack_o_lantern'],
  ['Jungle Leaves', 'jungle_leaves'],
  ['Jungle Log', 'jungle_log'],
  ['Jungle Planks', 'jungle_planks'],
  ['Jungle Sapling', 'jungle_sapling'],
  ['Lapis Block', 'lapis_block'],
  ['Lapis Ore', 'lapis_ore'],
  ['Lava', 'lava_still'],
  ['Lily Pad', 'lily_pad'],
  ['Lodestone', 'lodestone_side'],
  ['Magma', 'magma'],
  ['Mangrove Leaves', 'mangrove_leaves'],
  ['Mangrove Log', 'mangrove_log'],
  ['Mangrove Planks', 'mangrove_planks'],
  ['Melon', 'melon_side'],
  ['Moss Block', 'moss_block'],
  ['Mossy Cobblestone', 'mossy_cobblestone'],
  ['Mud', 'mud'],
  ['Mud Bricks', 'mud_bricks'],
  ['Mushroom Stem', 'mushroom_stem'],
  ['Mycelium', 'mycelium_side'],
  ['Nether Bricks', 'nether_bricks'],
  ['Nether Gold Ore', 'nether_gold_ore'],
  ['Nether Quartz Ore', 'nether_quartz_ore'],
  ['Nether Wart Block', 'nether_wart_block'],
  ['Netherite Block', 'netherite_block'],
  ['Netherrack', 'netherrack'],
  ['Note Block', 'note_block'],
  ['Oak Leaves', 'oak_leaves'],
  ['Oak Log', 'oak_log'],
  ['Oak Planks', 'oak_planks'],
  ['Oak Sapling', 'oak_sapling'],
  ['Observer', 'observer_front'],
  ['Obsidian', 'obsidian'],
  ['Orange Tulip', 'orange_tulip'],
  ['Oxeye Daisy', 'oxeye_daisy'],
  ['Packed Ice', 'packed_ice'],
  ['Pink Tulip', 'pink_tulip'],
  ['Podzol', 'podzol_side'],
  ['Polished Andesite', 'polished_andesite'],
  ['Polished Blackstone', 'polished_blackstone'],
  ['Polished Diorite', 'polished_diorite'],
  ['Polished Granite', 'polished_granite'],
  ['Poppy', 'poppy'],
  ['Prismarine', 'prismarine'],
  ['Prismarine Bricks', 'prismarine_bricks'],
  ['Pumpkin', 'pumpkin_side'],
  ['Purpur Block', 'purpur_block'],
  ['Quartz Block', 'quartz_block_side'],
  ['Quartz Bricks', 'quartz_bricks'],
  ['Raw Copper Block', 'raw_copper_block'],
  ['Raw Gold Block', 'raw_gold_block'],
  ['Raw Iron Block', 'raw_iron_block'],
  ['Red Concrete', 'red_concrete'],
  ['Red Mushroom Block', 'red_mushroom_block'],
  ['Red Sand', 'red_sand'],
  ['Red Sandstone', 'red_sandstone'],
  ['Red Tulip', 'red_tulip'],
  ['Red Wool', 'red_wool'],
  ['Redstone Block', 'redstone_block'],
  ['Redstone Lamp', 'redstone_lamp'],
  ['Redstone Ore', 'redstone_ore'],
  ['Rooted Dirt', 'rooted_dirt'],
  ['Sand', 'sand'],
  ['Sandstone', 'sandstone'],
  ['Scaffolding', 'scaffolding_side'],
  ['Sculk', 'sculk'],
  ['Sea Lantern', 'sea_lantern'],
  ['Shroomlight', 'shroomlight'],
  ['Slime Block', 'slime_block'],
  ['Smithing Table', 'smithing_table_front'],
  ['Smoker', 'smoker_front'],
  ['Smooth Stone', 'smooth_stone'],
  ['Snow', 'snow'],
  ['Soul Sand', 'soul_sand'],
  ['Soul Soil', 'soul_soil'],
  ['Sponge', 'sponge'],
  ['Spruce Leaves', 'spruce_leaves'],
  ['Spruce Log', 'spruce_log'],
  ['Spruce Planks', 'spruce_planks'],
  ['Spruce Sapling', 'spruce_sapling'],
  ['Stone', 'stone'],
  ['Stone Bricks', 'stone_bricks'],
  ['Sunflower', 'sunflower_front'],
  ['Target', 'target_side'],
  ['Terracotta', 'terracotta'],
  ['Tnt', 'tnt_side'],
  ['Tube Coral Block', 'tube_coral_block'],
  ['Tuff', 'tuff'],
  ['Warped Nylium', 'warped_nylium'],
  ['Warped Planks', 'warped_planks'],
  ['Warped Wart Block', 'warped_wart_block'],
  ['Water', 'water_still'],
  ['White Concrete', 'white_concrete'],
  ['White Tulip', 'white_tulip'],
  ['White Wool', 'white_wool'],
  ['Wither Rose', 'wither_rose']
];

export const ALL_ENTITIES: MenuOption[] = [
  ['Axolotl', 'axolotl'],
  ['Bat', 'bat'],
  ['Bee', 'bee'],
  ['Blaze', 'blaze'],
  ['Cat', 'cat'],
  ['Chicken', 'chicken'],
  ['Cow', 'cow'],
  ['Creeper', 'creeper'],
  ['Dolphin', 'dolphin'],
  ['Enderman', 'enderman'],
  ['Fox', 'fox'],
  ['Ghast', 'ghast'],
  ['Goat', 'goat'],
  ['Guardian', 'guardian'],
  ['Hoglin', 'hoglin'],
  ['Horse', 'horse'],
  ['Iron Golem', 'iron_golem'],
  ['Llama', 'llama'],
  ['Panda', 'panda'],
  ['Parrot', 'parrot'],
  ['Pig', 'pig'],
  ['Piglin', 'piglin'],
  ['Rabbit', 'rabbit'],
  ['Sheep', 'sheep'],
  ['Silverfish', 'silverfish'],
  ['Skeleton', 'skeleton'],
  ['Slime', 'slime'],
  ['Snow Golem', 'snow_golem'],
  ['Spider', 'spider'],
  ['Squid', 'squid'],
  ['Strider', 'strider'],
  ['Turtle', 'turtle'],
  ['Villager', 'villager'],
  ['Witch', 'witch'],
  ['Wolf', 'wolf'],
  ['Zombie', 'zombie']
];
